@extends('layouts.app')
@section('content')
@include('components.header')
@php $active = count(array_filter($loans, fn($l)=>in_array($l['status']??'', ['menunggu','disetujui','dipinjam'], true))); $fineTotal=array_sum(array_map(fn($l)=>(int)($l['denda']??0),$loans)); @endphp
<div class="history-top"><div class="profile"><div class="profile-avatar"></div><div><h1 class="serif" style="font-size:30px;color:var(--navy);margin:0">{{ session('auth.member.nama') }}</h1><div style="font-size:13px;color:var(--muted)">ID Anggota: {{ session('auth.member.id') }}</div></div></div><div style="display:flex;gap:32px"><div><small>Reservasi Aktif</small><strong style="display:block">{{ $active }} Buku</strong></div><div><small>Denda Berjalan</small><strong style="display:block">Rp {{ number_format($fineTotal,0,',','.') }}</strong></div></div></div>
<div class="history-tabs"><div class="tabs"><span class="tab active">Pemesanan & Barcode</span><span class="tab">Riwayat Lengkap Peminjaman</span></div></div>
<div class="history-content"><h2 class="serif" style="color:var(--navy)">Reservasi Sedang Berjalan</h2><div class="reservation-grid">
@forelse($loans as $loan)<div class="reservation"><div class="mini-cover"><div class="cover-placeholder">BOOK</div></div><div style="flex:1"><span class="status {{ ($loan['status']??'')==='ditolak'?'danger':(($loan['status']??'')==='menunggu'?'warn':'') }}">{{ strtoupper($loan['status'] ?? '-') }}</span><h3 class="serif" style="color:var(--navy);margin:16px 0 4px">{{ $loan['nama_buku'] ?? 'Buku' }}</h3><div style="font-size:13px;color:var(--muted)">Pesan: {{ !empty($loan['tanggal_pesan']) ? \Carbon\Carbon::parse($loan['tanggal_pesan'])->format('d M Y H:i') : '-' }}</div><div class="code"><span>KODE UNIK:</span><b>{{ $loan['kode_barcode'] ?? '-' }}</b></div>@if(($loan['status']??'')==='disetujui')<a class="btn btn-primary" href="{{ route('loan.barcode',$loan['_id']) }}">Lihat Barcode</a>@endif</div></div>@empty<div class="notice">Belum ada riwayat peminjaman.</div>@endforelse
</div><h2 class="serif" style="color:var(--navy);margin-top:48px">Riwayat Transaksi Peminjaman</h2><table class="data-table"><thead><tr><th>Judul Buku</th><th>Tanggal Pinjam</th><th>Jatuh Tempo</th><th>Tanggal Kembali</th><th>Status</th><th>Denda</th></tr></thead><tbody>@forelse($loans as $loan)<tr><td><b>{{ $loan['nama_buku'] ?? '-' }}</b></td><td>{{ !empty($loan['tanggal_peminjam']) ? \Carbon\Carbon::parse($loan['tanggal_peminjam'])->format('d M Y') : '-' }}</td><td>{{ !empty($loan['tanggal_pengembalian']) ? \Carbon\Carbon::parse($loan['tanggal_pengembalian'])->format('d M Y') : '-' }}</td><td>{{ !empty($loan['tanggal_dikembalikan']) ? \Carbon\Carbon::parse($loan['tanggal_dikembalikan'])->format('d M Y') : '-' }}</td><td>{{ ucfirst($loan['status'] ?? '-') }}</td><td>Rp {{ number_format((int)($loan['denda'] ?? 0),0,',','.') }}</td></tr>@empty<tr><td colspan="6">Belum ada transaksi.</td></tr>@endforelse</tbody></table></div>
@include('components.footer')
@endsection
