@extends('layouts.app')
@section('content')
@include('components.header')
<section class="hero"><div class="hero-copy"><span class="pill">Perpustakaan Umum Terakreditasi A</span><h1>Buka Jendela Dunia Melalui Halaman Ilmu</h1><p>Cari, pesan, dan pinjam koleksi buku dengan praktis. Menghubungkan pembaca dengan sejarah, sains, dan masa depan.</p><form class="search" action="{{ route('catalog') }}"><input name="q" placeholder="Cari judul buku, penulis, atau topik sains..."><button class="btn btn-green">Cari Buku</button></form><div class="stats"><div class="stat"><strong>{{ number_format($bookCount) }}</strong><span>Koleksi Buku Aktif</span></div><div class="stat"><strong>{{ number_format($memberCount) }}</strong><span>Anggota Aktif</span></div><div class="stat"><strong>99.4%</strong><span>Tingkat Kepuasan</span></div></div></div><div class="hero-img"><img src="https://www.figma.com/api/mcp/asset/7c8a4f1d-9f11-4db4-aed1-0c9f6e0e8f44.png" alt="Interior perpustakaan"></div></section>
<section><div class="section-title"><div class="eyebrow">Panduan Anggota</div><h2>Alur Praktis Peminjaman Buku</h2></div><div class="steps">@foreach([['Daftar Akun','Buat akun keanggotaan Pustaka Digital secara daring.','01'],['Cari Buku','Telusuri katalog untuk menemukan buku pilihan Anda.','02'],['Reservasi Buku','Pesan buku secara online dan tentukan tanggal pengambilan.','03'],['Ambil di Perpustakaan','Tunjukkan barcode reservasi kepada petugas.','04']] as $s)<div class="step"><div class="step-top"><span class="step-icon">▣</span><span class="step-no">{{ $s[2] }}</span></div><h3>{{ $s[0] }}</h3><p>{{ $s[1] }}</p></div>@endforeach</div></section>
<section><div class="section-title" style="text-align:left"><div class="eyebrow">Koleksi</div><h2>Koleksi Buku Terbaru</h2></div><div class="books">@forelse($books as $book)@include('components.book-card',['book'=>$book,'borrowed'=>(($book['stock_buku']??0)<=0)])@empty<div class="notice">Belum ada koleksi buku.</div>@endforelse</div></section>
<section style="background:#fff"><div class="section-title"><div class="eyebrow">Kategori Buku Terpopuler</div><h2>Telusuri Berdasarkan Kategori</h2></div><div class="categories">@foreach([['Fiksi','Fiksi & Sastra'],['Sains','Sains & Quantum'],['Teknologi','Teknologi & Kode'],['Sejarah','Sejarah Nusantara'],['Sastra','Sastra'],['Biografi','Biografi Tokoh']] as $c)<a class="cat" href="{{ route('catalog',['q'=>$c[1]]) }}"><div class="cat-body"><h3>{{ $c[0] }}</h3><span>Telusuri koleksi</span></div></a>@endforeach</div></section>
<section class="testimonials"><div class="section-title"><div class="eyebrow">Testimoni Anggota</div><h2>Suara Pengunjung Pustaka</h2></div><div class="quote">“Pemesanan buku menjadi jauh lebih praktis. Saya bisa melihat status peminjaman tanpa harus datang ke perpustakaan.”</div></section>
@include('components.footer')
@endsection
